### ISSUE TITLE
Upgrade Kubernetes server

### ISSUE THREAD

**Issue by zackgalbreath** [spack/spack-infrastructure#34]
The version of Kubernetes we're using (1.13) is deprecated and no longer supported by Amazon EKS.

Consider the pros & cons of recreating the cluster from scratch instead of upgrading it in place.

This may also be a good opportunity to create our test/backup cluster so we can more easily test changes without affecting our production services.

cc @opadron

**Comment by mvandenburgh** [comment]
Closed by #372
